// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsAgregator.Data;

#nullable disable

namespace NewsAgregator.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    [Migration("20221227101742_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewsAgregator.Models.Category", b =>
                {
                    b.Property<string>("SourceName")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(2);

                    b.HasKey("SourceName", "Name");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("NewsAgregator.Models.NewsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceName")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SourceName", "CategoryName");

                    b.ToTable("NewsItems");
                });

            modelBuilder.Entity("NewsAgregator.Models.Source", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Sources");

                    b.HasData(
                        new
                        {
                            Name = "Mail.ru",
                            Link = "https://news.mail.ru/rss/",
                            Type = 0
                        },
                        new
                        {
                            Name = "RT",
                            Link = "https://russian.rt.com/rss",
                            Type = 0
                        },
                        new
                        {
                            Name = "Лента",
                            Link = "https://lenta.ru/rss",
                            Type = 0
                        },
                        new
                        {
                            Name = "Астрей",
                            Link = "astrey",
                            Type = 1
                        });
                });

            modelBuilder.Entity("NewsAgregator.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@mail.ru",
                            Password = "123456",
                            Role = 1
                        });
                });

            modelBuilder.Entity("NewsAgregator.Models.Category", b =>
                {
                    b.HasOne("NewsAgregator.Models.Source", "Sourse")
                        .WithMany("Categories")
                        .HasForeignKey("SourceName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sourse");
                });

            modelBuilder.Entity("NewsAgregator.Models.NewsItem", b =>
                {
                    b.HasOne("NewsAgregator.Models.Source", "Source")
                        .WithMany("NewsItems")
                        .HasForeignKey("SourceName");

                    b.HasOne("NewsAgregator.Models.Category", "Category")
                        .WithMany("NewsItems")
                        .HasForeignKey("SourceName", "CategoryName");

                    b.Navigation("Category");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("NewsAgregator.Models.Category", b =>
                {
                    b.Navigation("NewsItems");
                });

            modelBuilder.Entity("NewsAgregator.Models.Source", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("NewsItems");
                });
#pragma warning restore 612, 618
        }
    }
}
